version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/vonage-rails-devise-2fa-demo
      - gem_data:/usr/local/bundle
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "./start.sh"]
  db:
    image: mysql:8.0.21
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'vonage_rails_devise_2fa_demo_development'
volumes:
  mysql_data:
  gem_data:
